services:
  postgres_sso:
    image: postgres
    restart: always
    volumes:
      - postgres_sso_data:/data/db
    environment:
      - 'POSTGRES_USER=learnify'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_DB=learnify_sso'
    ports:
      - 5431:5432
  postgres_plans:
    image: postgres
    restart: always
    volumes:
      - postgres_plans_data:/data/db
    environment:
      - 'POSTGRES_USER=learnify'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_DB=learnify_plans'
    ports:
      - 5432:5432
  redis:
    image: redis
    restart: always
    volumes:
      - redis_data:/data/data
    environment:
      - 'REDIS_PASSWORD=password'
    ports:
      - 6378:6379
volumes:
  postgres_sso_data:
  postgres_plans_data:
  redis_data:
