services:
  postgres_sso:
    image: postgres
    restart: always
    volumes:
      - postgres_sso_data:/data/db
    environment:
      - 'POSTGRES_USER=learnify'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_DB=learnify_sso'
    ports:
      - 5431:5432
  postgres_plans:
    image: postgres
    restart: always
    volumes:
      - postgres_plans_data:/data/db
    environment:
      - 'POSTGRES_USER=learnify'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_DB=learnify_sso'
    ports:
      - 5432:5432
volumes:
  postgres_sso_data:
  postgres_plans_data:
