services:
  postgres_sso:
    image: postgres
    restart: always
    volumes:
      - postgres_sso_data:/data/db
    environment:
      - 'POSTGRES_USER=learnify'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_DB=learnify_sso'
    ports:
      - 5431:5432
  postgres_plans:
    image: postgres
    restart: always
    volumes:
      - postgres_plans_data:/data/db
    environment:
      - 'POSTGRES_USER=learnify'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_DB=learnify_plans'
    ports:
      - 5432:5432
  redis:
    image: redis
    restart: always
    volumes:
      - redis_data:/data/data
    environment:
      - 'REDIS_PASSWORD=password'
    ports:
      - 6378:6379
  localstack:
    container_name: localstack-main
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"          
      - "127.0.0.1:4510-4559:4510-4559" 
    environment:
      - SERVICES=iam,sqs,lambda,events,logs
      - DEBUG=-0
    volumes:
      #- ./bootstrap:/etc/localstack/init/ready.d
      - localstack-data:/data/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: order
    ports:
      - 27017:27017
volumes:
  postgres_sso_data:
  postgres_plans_data:
  redis_data:
  localstack-data:
  mongodb-data: