spring:
  application:
    name: order

redis:
  host: localhost
  port: 6378

aws:
  credentials:
    access-key: fakeAccessKey
    secret-key: fakeSecretKey
    region: us-east-1
  endpoint: http://localhost:4566
  services:
    queue:
        url:
          payment: https://localhost.localstack.cloud:4566/000000000000/payment
          signature: https://localhost.localstack.cloud:4566/000000000000/signature
          cancel-signature: https://localhost.localstack.cloud:4566/000000000000/cancel-signature
        name:
          signature: signature
          return-signature: return-signature
          return-payment: return-payment

api:
  order:
    idempotency:
      time: 1
  plans:
    url: http://localhost:8082

server:
  port: 8083