spring:
  application:
    name: order

redis:
  host: localhost
  port: 6378

aws:
  credentials:
    access-key: fakeAccessKey
    secret-key: fakeSecretKey
    region: us-east-1
  endpoint: http://localhost:4566
  services:
    queue:
      payment-url: https://localhost.localstack.cloud:4566/000000000000/payment
      signature-url: https://localhost.localstack.cloud:4566/000000000000/signature

api:
  order:
    idempotency:
      time: 1

server:
  port: 8083