
spring:
  application:
    name: gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: sso
          uri: http://localhost:8081
          predicates:
            - Path=/auth/{segment},/users,/users/{segment}
        - id: plans
          uri: http://localhost:8082
          predicates:
            - Path=/plans,/plans/{segment}

api:
  sso:
    url: http://localhost:8081
