spring:
  application:
    name: sso

  datasource:
    url: jdbc:postgresql://localhost:5431/learnify_sso
    username: learnify
    password: password
    driver-class-name: org.postgresql.Driver

stripe:
  api-key: sk_test_51QLWRPBOD9n8dy044RM36aMjnMNXFsEwk7qgMwA9DEh2obcAOL3DR66QUumvnyPHeikvScA0nMYIl1atHFmI7xam00lUjnw1US

api:
  security:
    token:
      secret: 3afd43e7-12db-4e68-a157-bd078b611dcd
      expireIn: 600
      issuer: learnify

server:
  port: 8081