spring:
  application:
    name: payment

aws:
  credentials:
    access-key: fakeAccessKey
    secret-key: fakeSecretKey
    region: us-east-1
  endpoint: http://localhost:4566
  services:
    queue:
      payment-url: https://localhost.localstack.cloud:4566/000000000000/signature_plan

server:
  port: 8084