spring:
  application:
    name: payment

aws:
  credentials:
    access-key: fakeAccessKey
    secret-key: fakeSecretKey
    region: us-east-1
  endpoint: http://localhost:4566
  services:
    queue:
      url:
        return-payment: https://localhost.localstack.cloud:4566/000000000000/return-payment
        return-cancel-signature: https://localhost.localstack.cloud:4566/000000000000/return-cancel-signature
      name:
        payment: payment
        cancel-signature: cancel-signature

stripe:
  api-key: sk_test_51QLWRPBOD9n8dy044RM36aMjnMNXFsEwk7qgMwA9DEh2obcAOL3DR66QUumvnyPHeikvScA0nMYIl1atHFmI7xam00lUjnw1US

server:
  port: 8084