spring:
  profiles:
    active: seed
  application:
    name: plans

  datasource:
    url: jdbc:postgresql://localhost:5432/learnify_plans
    username: learnify
    password: password
    driver-class-name: org.postgresql.Driver

aws:
  credentials:
    access-key: fakeAccessKey
    secret-key: fakeSecretKey
    region: us-east-1
  endpoint: http://localhost:4566
  services:
    queue:
      url:
        return-signature: https://localhost.localstack.cloud:4566/000000000000/return-signature
      name:
        signature: signature

stripe:
  api-key: sk_test_51QLWRPBOD9n8dy044RM36aMjnMNXFsEwk7qgMwA9DEh2obcAOL3DR66QUumvnyPHeikvScA0nMYIl1atHFmI7xam00lUjnw1US

server:
  port: 8082