spring:
  application:
    name: plans

  datasource:
    url: jdbc:postgresql://localhost:5432/learnify_plans
    username: learnify
    password: password
    driver-class-name: org.postgresql.Driver

aws:
  credentials:
    access-key: fakeAccessKey
    secret-key: fakeSecretKey
    region: us-east-1
  endpoint: http://localhost:4566
  services:
    queue:
      signature-url: https://localhost.localstack.cloud:4566/000000000000/signature
      return-signature: https://localhost.localstack.cloud:4566/000000000000/return-signature
server:
  port: 8082